#!/usr/bin/env bash
# Good luck, Bad luck, Best School
n=1
while [ $n -le 10 ]
do
        if [ $n -eq 4 ]
        then
                echo "bad luck"
        elif [ $n -eq 8 ]
        then
                echo "Good luck"
        else
                echo "Best School"
        fi
        n=$((n+1))
done
